//! StatusNotifierItem tray via ksni, served from a background thread.

use super::{
    escape_mnemonic, pac_index, proxy_index, Sink, TrayEvent, TrayMenu, APP_ID, PAC_RULES,
    PROXY_MODES,
};
use ksni::menu::{RadioGroup, RadioItem, StandardItem, SubMenu};
use ksni::{MenuItem, ToolTip};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{channel, Receiver, Sender};
use std::sync::Arc;

pub struct LinuxTray {
    /// Closed on drop, which shuts the service down.
    updates: Sender<TrayMenu>,
    state: Arc<State>,
}

#[derive(Default)]
struct State {
    spawned: AtomicBool,
    /// No StatusNotifierWatcher is on the bus right now.
    offline: AtomicBool,
}

impl LinuxTray {
    pub fn start(menu: TrayMenu, sink: Sink) -> Self {
        let (updates, rx) = channel();
        let state = Arc::new(State::default());
        let thread_state = Arc::clone(&state);
        let spawned = std::thread::Builder::new()
            .name("tray".into())
            .spawn(move || serve(menu, sink, thread_state, rx));
        if let Err(err) = spawned {
            tracing::warn!("tray thread failed to start: {err}");
        }
        Self { updates, state }
    }

    pub fn is_available(&self) -> bool {
        self.state.spawned.load(Ordering::Acquire) && !self.state.offline.load(Ordering::Acquire)
    }

    pub fn update(&self, menu: TrayMenu) {
        let _ = self.updates.send(menu);
    }
}

fn serve(menu: TrayMenu, sink: Sink, state: Arc<State>, updates: Receiver<TrayMenu>) {
    use ksni::TrayMethods;
    let runtime = match tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
    {
        Ok(runtime) => runtime,
        Err(err) => {
            tracing::warn!("tray runtime failed to start: {err}");
            return;
        }
    };
    let tray = SniTray {
        menu,
        sink,
        state: Arc::clone(&state),
    };
    // Keep waiting for a watcher that appears later (e.g. plasmashell
    // starting after us); `is_available` stays false until it registers.
    let handle = match runtime.block_on(tray.assume_sni_available(true).spawn()) {
        Ok(handle) => handle,
        Err(err) => {
            tracing::warn!("system tray unavailable: {err}");
            return;
        }
    };
    state.spawned.store(true, Ordering::Release);
    while let Ok(mut menu) = updates.recv() {
        // Only the newest state matters.
        while let Ok(newer) = updates.try_recv() {
            menu = newer;
        }
        runtime.block_on(handle.update(move |tray| tray.menu = menu));
    }
    runtime.block_on(handle.shutdown());
}

struct SniTray {
    menu: TrayMenu,
    sink: Sink,
    state: Arc<State>,
}

impl SniTray {
    fn send(&self, event: TrayEvent) {
        (self.sink)(event);
    }
}

fn item(label: &str, event: TrayEvent) -> MenuItem<SniTray> {
    StandardItem {
        label: escape_mnemonic(label, '_'),
        activate: Box::new(move |tray: &mut SniTray| tray.send(event)),
        ..Default::default()
    }
    .into()
}

fn radio(labels: &[&str], selected: usize, event: fn(usize) -> TrayEvent) -> MenuItem<SniTray> {
    RadioGroup {
        selected,
        select: Box::new(move |tray: &mut SniTray, index| tray.send(event(index))),
        options: labels
            .iter()
            .map(|label| RadioItem {
                label: escape_mnemonic(label, '_'),
                ..Default::default()
            })
            .collect(),
    }
    .into()
}

impl ksni::Tray for SniTray {
    fn id(&self) -> String {
        APP_ID.into()
    }

    fn title(&self) -> String {
        "juicity".into()
    }

    /// The theme icon wins when installed; the pixmaps are the fallback.
    fn icon_name(&self) -> String {
        APP_ID.into()
    }

    fn icon_pixmap(&self) -> Vec<ksni::Icon> {
        // Raw ARGB32 big-endian pixels generated by build.rs.
        const D16: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray_16_argb.raw"));
        const D32: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray_32_argb.raw"));
        const D48: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray_48_argb.raw"));
        [(16, D16), (32, D32), (48, D48)]
            .into_iter()
            .map(|(size, data)| ksni::Icon {
                width: size,
                height: size,
                data: data.to_vec(),
            })
            .collect()
    }

    fn tool_tip(&self) -> ToolTip {
        ToolTip {
            title: "juicity".into(),
            description: self.menu.tooltip(),
            ..Default::default()
        }
    }

    fn activate(&mut self, _x: i32, _y: i32) {
        self.send(TrayEvent::ToggleWindow);
    }

    fn menu(&self) -> Vec<MenuItem<Self>> {
        let model = &self.menu.model;
        let text = &self.menu.labels;
        let proxy = vec![
            radio(
                &[&text.off, &text.pac, &text.global],
                proxy_index(model.proxy_mode),
                |i| TrayEvent::SetProxyMode(PROXY_MODES[i.min(PROXY_MODES.len() - 1)]),
            ),
            MenuItem::Separator,
            radio(
                &[&text.bypass_china, &text.gfw_list],
                pac_index(model.pac_rule),
                |i| TrayEvent::SetPacRule(PAC_RULES[i.min(PAC_RULES.len() - 1)]),
            ),
            item(&text.update_rules, TrayEvent::UpdateRules),
        ];
        let mut nodes = Vec::new();
        if !model.nodes.is_empty() {
            let names: Vec<&str> = model.nodes.iter().map(String::as_str).collect();
            // Out of range checks nothing.
            nodes.push(radio(
                &names,
                model.active.unwrap_or(usize::MAX),
                TrayEvent::SelectNode,
            ));
            nodes.push(MenuItem::Separator);
        }
        nodes.push(item(&text.import_clipboard, TrayEvent::ImportClipboard));
        vec![
            StandardItem {
                label: escape_mnemonic(&text.status, '_'),
                enabled: false,
                ..Default::default()
            }
            .into(),
            item(&text.connect, TrayEvent::ToggleConnection),
            SubMenu {
                label: escape_mnemonic(&text.system_proxy, '_'),
                submenu: proxy,
                ..Default::default()
            }
            .into(),
            SubMenu {
                label: escape_mnemonic(&text.nodes, '_'),
                submenu: nodes,
                ..Default::default()
            }
            .into(),
            MenuItem::Separator,
            item(&text.open, TrayEvent::Open),
            item(&text.edit_nodes, TrayEvent::ShowNodes),
            item(&text.logs, TrayEvent::ShowLogs),
            item(&text.settings, TrayEvent::ShowSettings),
            item(&text.about, TrayEvent::ShowAbout),
            MenuItem::Separator,
            item(&text.quit, TrayEvent::Quit),
        ]
    }

    fn watcher_online(&self) {
        tracing::info!("system tray registered");
        self.state.offline.store(false, Ordering::Release);
    }

    fn watcher_offline(&self, reason: ksni::OfflineReason) -> bool {
        tracing::warn!("no system tray host: {reason:?}");
        self.state.offline.store(true, Ordering::Release);
        // Keep the service so the icon returns with the watcher.
        true
    }
}
